name: Workflow Run tests

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test number'
        required: true
        type: number

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check workflow_run context
        run: |
          echo "${{ toJson(github) }}"
          echo "Test input: ${{ inputs.test || github.event.workflow_run.pull_requests[0].number }}"